### ISSUE TITLE
Has my hubble crashed and why?

### ISSUE THREAD

**Issue by n00b21337** [farcasterxyz/hub-monorepo#1698] opened 2024-02-13 17:03 UTC
Every few days I get something like this and seems like nothing is happening anymore. Then I go and restart docker
and graphs are alive again.
![image](https://github.com/farcasterxyz/hub-monorepo/assets/8969767/4d89c564-968a-456a-b6a2-4923116d521e)

All I see from LOGS is this, not sure what this means and why this happens.

```
hubble_1  | {"level":30,"time":1707734868060,"pid":1,"hostname":"ae44e9bfb117","component":"Hub","errCode":"bad_request.duplicate","peerId":"12D3KooW9vyVcQEystJjTp3qy1YjQimTSQvNodDnXiUatQG1UxN2","origin":"12D3KooWH9ojvuodLfc6bVyWArFaVAPgaKFiLFqH4Em48KQpSfwL","hash":"0x7d80aed745b174656e88c41104d0919e295ffa66","msgId":"fYCu10WxdGVuiMQRBNCRnilf+mY","msg":"Received bad gossip message from peer"}
hubble_1  | {"level":40,"time":1707734868060,"pid":1,"hostname":"ae44e9bfb117","component":"Hub","submittedMessage":{"timestamp":1707730776000,"hash":"0x9ffa273bef2915ce332339d6168139c055894fb9","fid":286449,"type":5},"source":"gossip","errCode":"bad_request.duplicate","source":"gossip","msg":"submitMessage error: message has already been merged"}
```

**Comment by sanjayprabhu** [comment] 2024-02-28 22:26
Hmm, those are the last log lines from hubble? Is the docker container running? Next time this happens, could you show paste the output of the following commands:
`./hubble.sh logs | tail -n 100`
and 
`sudo docker ps`

**Comment by sds** [comment] 2024-03-07 01:29
Closing due to age. Recommend you upgrade to the latest version (1.10.9) at type of writing and if you are able to reproduce include the full log output. Thank you!

**Closed by sds** 2024-03-07 01:29 UTC
Labels: s-noop
