### ISSUE TITLE
Replicate Data in Postgres: fnames failed to sync

### ISSUE THREAD

**Issue by rhizobtc** [farcasterxyz/hub-monorepo#987] opened 2023-05-19 19:36 UTC
**What is the bug?**
When running a local docker image, fnames from prior to the initial setup fail to sync. 

**How can it be reproduced? (optional)**
Resync a fresh docker image

**Comment by varunsrin** [comment] 2023-07-05 02:23
duplicate of https://github.com/farcasterxyz/hub-monorepo/issues/1040

**Closed by varunsrin** 2023-07-05 02:23 UTC
Labels: s-triage
