### ISSUE TITLE
bug: unable to peer hubble

### ISSUE THREAD

**Issue by Drewsapple** [farcasterxyz/hub-monorepo#1137] opened 2023-07-15 00:48 UTC
**What is the bug?**
I'm trying to run hubble on a local machine, behind a NAT. I tried forwarding ports `2282`, and then `2283` as well when that didn't let me connect to even the bootstrap node.

**How can it be reproduced? (optional)**
My entire setup starting with a clone at commit 8d0d87d

- Initial docker command 
```
(hubble) $ docker compose run hubble yarn identity create
WARN[0000] The "ETH_RPC_URL" variable is not set. Defaulting to a blank string. 
WARN[0000] The "ETH_MAINNET_RPC_URL" variable is not set. Defaulting to a blank string. 
WARN[0000] The "FC_NETWORK_ID" variable is not set. Defaulting to a blank string. 
WARN[0000] The "BOOTSTRAP_NODE" variable is not set. Defaulting to a blank string. 
yarn run v1.22.19
$ node build/cli.js identity create
(node:27) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
file:///home/node/app/apps/hubble/build/cli.js:334
        throw new Error(err);
              ^

Error: Error: EACCES: permission denied, open '/home/node/app/apps/hubble/.hub/default_id.protobuf'
    at writePeerId (file:///home/node/app/apps/hubble/build/cli.js:334:15)
    at async Command.<anonymous> (file:///home/node/app/apps/hubble/build/cli.js:347:13)

Node.js v20.2.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

- Fix permissions from docker container (my user outside the container is drewf)
```
(hubble) $ sudo chown -R drewf:drewf .rocks
(hubble) $ sudo chown -R drewf:drewf .hub
```

- run identity creation again
```
(hubble) $ docker compose run hubble yarn identity create
WARN[0000] The "ETH_RPC_URL" variable is not set. Defaulting to a blank string. 
WARN[0000] The "ETH_MAINNET_RPC_URL" variable is not set. Defaulting to a blank string. 
WARN[0000] The "FC_NETWORK_ID" variable is not set. Defaulting to a blank string. 
WARN[0000] The "BOOTSTRAP_NODE" variable is not set. Defaulting to a blank string. 
yarn run v1.22.19
$ node build/cli.js identity create
(node:27) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
{"level":30,"time":1689381159423,"pid":27,"hostname":"87876d5a3600","msg":"Wrote peerId: 12D3KooWNG6ktRNyXKXuXawqCnXRBZHQeuiAGCkaMiYt7RbGd6Zk to /home/node/app/apps/hubble/.hub/default_id.protobuf"}
{"level":30,"time":1689381159424,"pid":27,"hostname":"87876d5a3600","msg":"Wrote peerId: 12D3KooWNG6ktRNyXKXuXawqCnXRBZHQeuiAGCkaMiYt7RbGd6Zk to /home/node/app/apps/hubble/.hub/12D3KooWNG6ktRNyXKXuXawqCnXRBZHQeuiAGCkaMiYt7RbGd6Zk_id.protobuf"}
Done in 1.22s.
```

- set up .env

- start container
lots of logs grabbing fid/fnames but I think the relevant part is here, right after fname state catches up to the chain:
```
hubble-hubble-1  | {"level":30,"time":1689381782227,"pid":27,"hostname":"9858fa9fae46","component":"Hub","event":{"timestamp":1689374244,"name":"axg","owner":"0xc35c7ad865527d3a8b395eaf6268479b5fcf6b04"},"source":"fname-registry","msg":"submitUserNameProof success 327362896801792: fname axg assigned to fid: 16214 at timestamp 1689374244"}
hubble-hubble-1  | {"level":30,"time":1689381782230,"pid":27,"hostname":"9858fa9fae46","component":"Hub","event":{"timestamp":1689376325,"name":"wildmolasses","owner":"0xa6ecaf2777c7c3898359a4388b8913afd7e0248d"},"source":"fname-registry","msg":"submitUserNameProof success 327362896814080: fname wildmolasses assigned to fid: 16215 at timestamp 1689376325"}
hubble-hubble-1  | {"level":30,"time":1689381782250,"pid":27,"hostname":"9858fa9fae46","component":"EthEventsProvider","blockNumber":9347125,"msg":"new block: 9347125"}
hubble-hubble-1  | {"level":30,"time":1689381782292,"pid":27,"hostname":"9858fa9fae46","component":"FNameRegistryEventsProvider","msg":"Fetched 16211 fname events upto 16211"}
hubble-hubble-1  | {"level":30,"time":1689381782292,"pid":27,"hostname":"9858fa9fae46","component":"SyncEngine","rootHash":"","msg":"Sync engine initialized"}
hubble-hubble-1  | {"level":30,"time":1689381782294,"pid":27,"hostname":"9858fa9fae46","component":"Node","function":"createNode","allowedPeerIds":[],"msg":"!!! PEER-ID RESTRICTIONS ENABLED !!!"}
hubble-hubble-1  | {"level":30,"time":1689381782361,"pid":27,"hostname":"9858fa9fae46","component":"Node","identity":"12D3KooWNG6ktRNyXKXuXawqCnXRBZHQeuiAGCkaMiYt7RbGd6Zk","addresses":["/ip4/75.139.73.214/tcp/2282/p2p/12D3KooWNG6ktRNyXKXuXawqCnXRBZHQeuiAGCkaMiYt7RbGd6Zk"],"msg":"Starting libp2p"}
hubble-hubble-1  | {"level":30,"time":1689381783877,"pid":27,"hostname":"9858fa9fae46","component":"ConnectionFilter","peerId":"12D3KooWQaNFSaNLfsa69QtDiwX9SNHV3VPqnRUeHXCuM3G8yknG","filter":"denyOutboundEncryptedConnection","msg":"denied a connection"}
hubble-hubble-1  | {"level":50,"time":1689381783879,"pid":27,"hostname":"9858fa9fae46","component":"Node","err":{"type":"AggregateError","message":"All promises were rejected","stack":"AggregateError: All promises were rejected","aggregateErrors":[{"type":"Error","message":"The multiaddr connection is blocked by gater.acceptEncryptedConnection","stack":"Error: The multiaddr connection is blocked by gater.acceptEncryptedConnection\n    at DefaultUpgrader.upgradeOutbound (file:///home/node/app/node_modules/libp2p/dist/src/upgrader.js:203:35)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async TCP.dial (file:///home/node/app/node_modules/@libp2p/tcp/dist/src/index.js:51:22)\n    at async DefaultTransportManager.dial (file:///home/node/app/node_modules/libp2p/dist/src/transport-manager.js:78:20)\n    at async DialRequest.dialAction (file:///home/node/app/node_modules/libp2p/dist/src/connection-manager/dialer/index.js:195:20)\n    at async file:///home/node/app/node_modules/libp2p/dist/src/connection-manager/dialer/dial-request.js:67:28\n    at async Promise.any (index 0)\n    at async DialRequest.run (file:///home/node/app/node_modules/libp2p/dist/src/connection-manager/dialer/dial-request.js:53:20)\n    at async DefaultDialer.dial (file:///home/node/app/node_modules/libp2p/dist/src/connection-manager/dialer/index.js:107:32)\n    at async DefaultConnectionManager.openConnection (file:///home/node/app/node_modules/libp2p/dist/src/connection-manager/index.js:306:32)","code":"ERR_CONNECTION_INTERCEPTED"}]},"msg":"Failed to connect to peer at address: /dns/testnet1.farcaster.xyz/tcp/2282"}
hubble-hubble-1  | {"level":30,"time":1689381794481,"pid":27,"hostname":"9858fa9fae46","component":"EthEventsProvider","blockNumber":9347126,"msg":"new block: 9347126"}
hubble-hubble-1  | {"level":30,"time":1689381806696,"pid":27,"hostname":"9858fa9fae46","component":"EthEventsProvider","blockNumber":9347127,"msg":"new block: 9347127"}
hubble-hubble-1  | {"level":30,"time":1689381812735,"pid":27,"hostname":"9858fa9fae46","component":"FNameRegistryEventsProvider","msg":"Fetched 0 fname events upto 16211"}
hubble-hubble-1  | {"level":30,"time":1689381818891,"pid":27,"hostname":"9858fa9fae46","component":"EthEventsProvider","blockNumber":9347128,"msg":"new block: 9347128"}
hubble-hubble-1  | {"level":30,"time":1689381842944,"pid":27,"hostname":"9858fa9fae46","component":"FNameRegistryEventsProvider","msg":"Fetched 0 fname events upto 16211"}
hubble-hubble-1  | {"level":30,"time":1689381867719,"pid":27,"hostname":"9858fa9fae46","component":"EthEventsProvider","blockNumber":9347129,"msg":"new block: 9347129"}
```

**Additional context (optional)**
I think this is related to #1127, but I didn't want to pollute that issue with all of my logs if it wasn't the case. Sorry if it's a duplicate.

**Comment by r-ae-i** [comment] 2023-07-15 09:09
I did setup Hubble last night and have the same issue. Although onchain data synced, I still get `Sync Status: No peers`

**Comment by Drewsapple** [comment] 2023-07-15 13:48
> @Drewsapple whats your peer id? 

Offline rn but here it is from the above logs 12D3KooWNG6ktRNyXKXuXawqCnXRBZHQeuiAGCkaMiYt7RbGd6Zk

**Comment by varunsrin** [comment] 2023-07-15 16:07
so i think both of you aren't done with step 3 in the setup instructions here: https://www.thehubble.xyz/intro/networks.html#mainnet

@r-ae-i i see your pr, but need a small update before i can merge.

@Drewsapple you'll need to add your peer id to that list, and once thats merged, you'll be able to connect to mainnet.

**Comment by Drewsapple** [comment] 2023-07-15 16:08
I'm trying to peer on testnet, but can't connect to testnet1 over libp2p. 

Should I just try for mainnet?

**Comment by varunsrin** [comment] 2023-07-15 23:17
@Drewsapple what does your .env file look like? feel free to redact the keys in the node urls.

**Comment by Drewsapple** [comment] 2023-07-15 23:19
@varunsrin 
```bash
ETH_RPC_URL=https://eth-goerli.g.alchemy.com/v2/KEY
ETH_MAINNET_RPC_URL=https://eth-mainnet.g.alchemy.com/v2/KEY
FC_NETWORK_ID=2
BOOTSTRAP_NODE=/dns/testnet1.farcaster.xyz/tcp/2282
```

**Comment by varunsrin** [comment] 2023-07-16 16:27
closing as dupe of #1127 , this should be fixed with this change: https://github.com/farcasterxyz/hub-monorepo/pull/1151

**Closed by varunsrin** 2023-07-16 16:27 UTC
Labels: s-triage
