### ISSUE TITLE
npm ERR! 404  'pm2-runtime@*' is not in this registry. when run node

### ISSUE THREAD

**Issue by johnny24-dev** [farcasterxyz/hub-monorepo#1727] opened 2024-02-22 07:02 UTC
hubble-1  | npm ERR! A complete log of this run can be found in: /home/node/.npm/_logs/2024-02-22T06_54_16_314Z-debug-0.log
hubble-1  | npm ERR! code E404
hubble-1  | npm ERR! 404 Not Found - GET https://registry.npmjs.org/pm2-runtime - Not found
hubble-1  | npm ERR! 404 
hubble-1  | npm ERR! 404  'pm2-runtime@*' is not in this registry.
hubble-1  | npm ERR! 404 
hubble-1  | npm ERR! 404 Note that you can also install from a
hubble-1  | npm ERR! 404 tarball, folder, http url, or git url.
hubble-1  | 
hubble-1  | npm ERR! A complete log of this run can be found in: /home/node/.npm/_logs/2024-02-22T06_54_21_549Z-debug-0.log

**Comment by BlankerL** [comment] 2024-02-22 10:06
Same issue on my side.

**Comment by BlankerL** [comment] 2024-02-22 10:26
I can confirm that this issue was introduced in the recent two commits ([9bcaa9](https://github.com/farcasterxyz/hub-monorepo/commit/9bcaa9c111aae22a507a3556511b8a12f48cf434) and [660d86](https://github.com/farcasterxyz/hub-monorepo/commit/660d86f032817d271f79b69add7d88b48990afad)). I resolved it by reverting these two commits, and everything now functions correctly on my end.

For anyone experiencing the same problem, you can use the following commands to update your local repository to the latest commits, revert the last two commits, and then run the Docker:

```bash
git checkout main && git pull
git revert --no-commit HEAD~1^..HEAD  # This command will revert the last two commits
docker compose stop && docker compose up -d --force-recreate --pull always
```

@sds, please review your commits, as they might be causing issues for others upgrading and could potentially introduce network stability issue.

**Comment by sds** [comment] 2024-02-22 17:53
@johnny24-dev @BlankerL how are you running your hubs? Are you using the `hubble.sh` script, or running directly within the repo itself?

If directly within the repo, did you make sure to run `yarn install && yarn build` from the root of `hub-monorepo` before attempting to run via `yarn start`?

In short, I'm not able to reproduce your issue either with the `hubble.sh` script or running `yarn install && yarn build && yarn start` directly in `hub-monorepo` with the latest commit on `main` (660d86f032817d271f79b69add7d88b48990afad at time of writing).

More detail would be helpful—thanks!

**Comment by pyggie** [comment] 2024-02-22 18:24
I confirm the same issue when using `docker compose up`, fixed with `git checkout 71114df0` to use the 1.10.2 release. The `docker-compose.yml` file refers to pm2 but the docker images don't seem to be consistent.

**Comment by sds** [comment] 2024-02-22 18:31
If you are running directly from within the repo, then yes, you should check out the latest tagged release. Running against `main` should not be done in production.

When I run `git fetch --tags --force && git checkout @latest && docker compose up` everything works fine.

**Comment by sds** [comment] 2024-02-22 18:35
I see that our instructions don't mention the above note about using the `@latest` tag. I will update the instructions. Thanks for the report!

**Comment by BlankerL** [comment] 2024-02-22 19:07
Yes, I'm running `docker compose` in the `app/hubble` folder following the [upgrade instruction](https://www.thehubble.xyz/intro/install.html#upgrading-hubble-1) for Docker users. 

Maybe you could modify this page as people usually following the instructions.

**Comment by sds** [comment] 2024-02-22 19:20
Yes, that coupled with #1731 should clear things up. Sorry for the confusion, and thanks for reporting!

**Closed by sds** 2024-02-22 19:20 UTC
Labels: s-triage

**Comment by BlankerL** [comment] 2024-02-22 20:03
Sorry to bother, but the instructions under [Upgrading Hubble](https://www.thehubble.xyz/intro/install.html#upgrading-hubble-1), which I mentioned above, is not fixed yet. I created a PR (#1733) to modify the instruction.
