### ISSUE TITLE
Node doesnt install

### ISSUE THREAD

**Issue by dibenkodima** [farcasterxyz/hub-monorepo#2220] opened 2024-07-28 07:53 UTC
![image](https://github.com/user-attachments/assets/20908e55-b43c-4a30-8b58-8ea71946f03c)

**Comment by Father-Web3** [comment] 2024-07-28 11:55
Same problem tried to install the node on two different VPSs but the problem is the same for me, too

**Comment by soandwhat** [comment] 2024-07-28 14:02
I think everyone have the same problem.

**Comment by sds** [comment] 2024-10-04 04:16
Closing as answered.

**Closed by sds** 2024-10-04 04:16 UTC
Labels: s-triage
