### ISSUE TITLE
bug：hub cannot startup

### ISSUE THREAD

**Issue by Tonyce** [farcasterxyz/hub-monorepo#1480] opened 2023-10-10 07:29 UTC
**What is the bug?**
hub cannot startup

**Additional context (optional)**
{"level":30,"time":1696922814632,"pid":1,"hostname":"e7752c3619fd","component":"L2EventsProvider","blockNumber":110662018,"msg":"new block: 110662018"}
{"level":40,"time":1696922816197,"pid":1,"hostname":"e7752c3619fd","component":"SyncEngine","error":{"presentable":false,"name":"HubError"},"errMsg":"Deadline exceeded","peerId":"12D3KooWQSyPDa14MJUhwU9UcvCkipMVsPYCGoNpyRNS55y5gZ9W","peerContact":{"gossipAddress":{"address":"116.15.139.57","family":4,"port":2282,"dnsName":""},"rpcAddress":{"address":"116.15.139.57","family":4,"port":2283,"dnsName":""},"excludedHashes":["af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9","af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9","9de2e2088f1be3950fe971b0526cade9302dc067","fd7174ce5e6c3a7bbe809b4a9255b03a8d4d3b68","554470f60d432b183e0009569913f61b49e80e90","697a4fb8fb3c8e18da8c524329e2152b216ba808","3f426974b5408f0fffc4502bd4183eaa0ba73189"],"count":4558598,"hubVersion":"2023.10.4","network":1,"appVersion":"1.6.0"},"msg":"Diffsync: Failed to get peer state, skipping sync"}
{"level":30,"time":1696922818898,"pid":1,"hostname":"e7752c3619fd","component":"L2EventsProvider","blockNumber":110662020,"msg":"new block: 110662020"}
{"level":30,"time":1696922823190,"pid":1,"hostname":"e7752c3619fd","component":"L2EventsProvider","blockNumber":110662022,"msg":"new block: 110662022"}
{"level":30,"time":1696922825261,"pid":1,"hostname":"e7752c3619fd","component":"FNameRegistryEventsProvider","msg":"Fetched 0 fname events upto 20737"}
{"level":30,"time":1696922827450,"pid":1,"hostname":"e7752c3619fd","component":"L2EventsProvider","blockNumber":110662024,"msg":"new block: 110662024"}
{"level":30,"time":1696922831732,"pid":1,"hostname":"e7752c3619fd","component":"L2EventsProvider","blockNumber":110662027,"msg":"new block: 110662027"}
{"level":60,"time":1696922835209,"pid":1,"hostname":"e7752c3619fd","msg":"Forcing exit after grace period"}

**Comment by Tonyce** [comment] 2023-10-10 09:15
<img width="1920" alt="Screenshot 2023-10-10 at 15 27 33" src="https://github.com/farcasterxyz/hub-monorepo/assets/7351139/477516ef-6bbd-4c22-afc6-d37a822a683a">

**Comment by Tonyce** [comment] 2023-10-10 09:16
<img width="1918" alt="Screenshot 2023-10-10 at 16 45 42" src="https://github.com/farcasterxyz/hub-monorepo/assets/7351139/52bb160a-7642-4f1d-8cb5-4eb3fece7e02">

**Comment by TecSong** [comment] 2023-10-10 12:07
I have the same problem
`hubble-hubble-1  | {"level":40,"time":1696939530351,"pid":1,"hostname":"4ccf7866adb6","component":"Hub","event":{"blockNumber":108877896,"blockHash":"0xeafe5cb9d7544d0eb7104aeb475d0b2a46c5c6510bb041bbe94b1b9590a37c37","fid":16889,"type":"EVENT_TYPE_SIGNER"},"source":"l2-provider","errCode":"bad_request.duplicate","msg":"submitOnChainEvent error: onChainEvent already exists"}
hubble-hubble-1  | {"level":40,"time":1696939530351,"pid":1,"hostname":"4ccf7866adb6","component":"Hub","event":{"blockNumber":108877896,"blockHash":"0xeafe5cb9d7544d0eb7104aeb475d0b2a46c5c6510bb041bbe94b1b9590a37c37","fid":16892,"type":"EVENT_TYPE_SIGNER"},"source":"l2-provider","errCode":"bad_request.duplicate","msg":"submitOnChainEvent error: onChainEvent already exists"}
hubble-hubble-1  | {"level":40,"time":1696939530352,"pid":1,"hostname":"4ccf7866adb6","component":"Hub","event":{"blockNumber":108877896,"blockHash":"0xeafe5cb9d7544d0eb7104aeb475d0b2a46c5c6510bb041bbe94b1b9590a37c37","fid":16956,"type":"EVENT_TYPE_SIGNER"},"source":"l2-provider","errCode":"bad_request.duplicate","msg":"submitOnChainEvent error: onChainEvent already exists"}
hubble-hubble-1  | {"level":40,"time":1696939530352,"pid":1,"hostname":"4ccf7866adb6","component":"Hub","event":{"blockNumber":108877896,"blockHash":"0xeafe5cb9d7544d0eb7104aeb475d0b2a46c5c6510bb041bbe94b1b9590a37c37","fid":16956,"type":"EVENT_TYPE_SIGNER"},"source":"l2-provider","errCode":"bad_request.duplicate","msg":"submitOnChainEvent error: onChainEvent already exists"}
hubble-hubble-1  | {"level":40,"time":1696939530353,"pid":1,"hostname":"4ccf7866adb6","component":"Hub","event":{"blockNumber":108877896,"blockHash":"0xeafe5cb9d7544d0eb7104aeb475d0b2a46c5c6510bb041bbe94b1b9590a37c37","fid":16958,"type":"EVENT_TYPE_SIGNER"},"source":"l2-provider","errCode":"bad_request.duplicate","msg":"submitOnChainEvent error: onChainEvent already exists"}
hubble-hubble-1  | {"level":30,"time":1696939530384,"pid":1,"hostname":"4ccf7866adb6","component":"GossipNode","identity":"12D3KooWSakyQismXysr1HKfqjPKeWmMp6hkjEw38wbDKpF6EWiV","msg":"Stopped libp2p..."}
hubble-hubble-1  | {"level":30,"time":1696939534275,"pid":1,"hostname":"4ccf7866adb6","component":"L2EventsProvider","blockNumber":110670378,"msg":"new block: 110670378"}
hubble-hubble-1  | {"level":30,"time":1696939538297,"pid":1,"hostname":"4ccf7866adb6","component":"L2EventsProvider","blockNumber":110670380,"msg":"new block: 110670380"}
hubble-hubble-1  | {"level":30,"time":1696939542325,"pid":1,"hostname":"4ccf7866adb6","component":"L2EventsProvider","blockNumber":110670382,"msg":"new block: 110670382"}
hubble-hubble-1  | {"level":30,"time":1696939546392,"pid":1,"hostname":"4ccf7866adb6","component":"L2EventsProvider","blockNumber":110670384,"msg":"new block: 110670384"}
hubble-hubble-1  | {"level":30,"time":1696939550414,"pid":1,"hostname":"4ccf7866adb6","component":"L2EventsProvider","blockNumber":110670386,"msg":"new block: 110670386"}
hubble-hubble-1  | {"level":30,"time":1696939553935,"pid":1,"hostname":"4ccf7866adb6","component":"FNameRegistryEventsProvider","msg":"Fetched 0 fname events upto 20740"}
hubble-hubble-1  | {"level":30,"time":1696939554438,"pid":1,"hostname":"4ccf7866adb6","component":"L2EventsProvider","blockNumber":110670388,"msg":"new block: 110670388"}
hubble-hubble-1  | {"level":30,"time":1696939558467,"pid":1,"hostname":"4ccf7866adb6","component":"L2EventsProvider","blockNumber":110670390,"msg":"new block: 110670390"}
hubble-hubble-1  | {"level":60,"time":1696939560280,"pid":1,"hostname":"4ccf7866adb6","msg":"Forcing exit after grace period"}
hubble-hubble-1 exit`

**Comment by adityapk00** [comment] 2023-10-10 13:34
I think this is a duplicate of https://github.com/farcasterxyz/hub-monorepo/issues/1481. Please follow along on that bug

**Closed by adityapk00** 2023-10-10 13:34 UTC
Labels: s-triage
