### ISSUE TITLE
bug (replicate-data-postgres): User data type 6 is missing for new users

### ISSUE THREAD

**Issue by manan19** [farcasterxyz/hub-monorepo#1059] opened 2023-07-01 21:40 UTC
**What is the bug?**
Type 6 (fname) data is missing from the user_data table for recently signed-up users

![image](https://github.com/farcasterxyz/hub-monorepo/assets/377624/b731aaf7-f732-4d7a-b33d-f94d83d9b5df)
![image](https://github.com/farcasterxyz/hub-monorepo/assets/377624/229155a1-f024-4048-92da-c023af9882f7)

**How can it be reproduced? (optional)**
1. Run the replicator and let it sync
2. run query - `select * from user_data where fid = 14299`

cc @sds

**Comment by sds** [comment] 2023-07-02 21:44
Confirming I can reproduce locally. Just to confirm, are you running the example as-is? (e.g. against `nemes.farcaster.xyz:2283`?)

https://github.com/farcasterxyz/hub-monorepo/blob/a9da418dbc43f601accd921283888b4f7cdb4eb6/packages/hub-nodejs/examples/replicate-data-postgres/index.ts#L11

**Comment by manan19** [comment] 2023-07-02 23:06
Running as-is for the most part.

No docker. Yes, running against nemes. Writing to an Amazon RDS instance.

**Comment by varunsrin** [comment] 2023-07-05 02:18
might be related to https://github.com/farcasterxyz/hub-monorepo/issues/1076

**Comment by varunsrin** [comment] 2023-07-12 20:25
duplicate of #1076

**Closed by varunsrin** 2023-07-12 20:25 UTC
Labels: t-bug, help wanted, s-ready
